### PR TITLE
Using vs2017 and change to make test pass

### PR DESCRIPTION
**Pull request by xuzhg**
Using vs2017 and change to make test pass:

image

### CODE REVIEW

**Comment by xuzhg** [comment]
@egbertn

**Comment by egbertn** [comment]
thanks great!

**Comment by xuzhg** [comment]
1. You can use "$ref" to update the navigation property.
2. You can wait for the v4.0.1 feature to be implemented in the ODL.

Thanks!

**Comment by awaitJosh** [comment]
Hi @xuzhg,

I don´t really understand what to do here to solve the problem. I have a similar setup like this https://github.com/OData/WebApi/issues/992 . If I send a JSON-document to my Patch-controller the delta is null. I don´t know what I am missing and it would be great if you provide me a little example.

Kind regards

**Comment by xuzhg** [comment]
@awaitJosh As I know, so far, yes.

**Comment by awaitJosh** [comment]
Ok thank you!

**Comment by yuhong-l** [comment]
> @awaitJosh As I know, so far, yes.

@xuzhg  Hi, why you say Yes? Shouldn't it be supported to be done by only one patch?
 I saw you comment in another post said support for patching complex type is ok. https://github.com/OData/WebApi/issues/945#issuecomment-342227831

> If patch an entity with collection of complex type property, it should work. See test here

**Comment by xuzhg** [comment]
@yuhong-l Here "Yes" is meaning that you should write "multiple patch-actions for each related entity", I think. Patch "Complex Type" is absolutely working in current Web API OData. Do you meet some problems?

**Comment by hong1997** [comment]
@xuzhg   Thanks Sam, sorry for confuse 'complex type' and 'eneity'.
Actually, I want to use this patch for complex 'entity'.
Like an entity is nested in another 'entity'.
When patch an object as below, the Delta<Customer> value will be null.
Like:
Customer:
{
id:xxx
Addresss:
{
id:xxx
name:xxx
}
}

**Comment by alexandrevribeiro** [comment]
@xuzhg Although there's [this test](https://github.com/xuzhg/WebApiSample/blob/master/v6.x/WebApi6xFeaturesTest/Complex/ComplexTypeTest.cs) for the `Microsoft.AspNet.OData 6.1.0`, even updating my package from 6.0.0 to 6.1.0 I wasn't able to use a complex property (apparently a navigation prop) on a PATCH request...

**My entity:**
```javascript
{
   // Other props
    "risk": {
        "id": 2,
        "description": "Low"
    }
}
```
**The error I receive:**
```javascript
{
    "error": {
        // [...]
        "details": [
            {
                "code": "",
                "message": "Cannot apply PATCH to navigation property 'risk' on entity type 'Novajus.Model.RestModels.Litigation.LawsuitModel'."
            }
        ]
    }
}
```

**The question is...**
Is there a way of marking the `risk` property to not be a *Navigation Property*, but just a complex object?

I know what is making OData interpret this prop as Navigation is the fact it has a `public int Id { get; set; }`. So I could just rename the `Id` to something else, but I really want to use `Id` since it's the most appropriate word for what I want.

Thanks.

**Comment by xuzhg** [comment]
@alexandrevribeiro if it's only complaining about the `Id`, you can explicitly call `builder.ComplexType<..>()` to mark the type as complex type.

**Comment by alexandrevribeiro** [comment]
Great. I'll try it out and let you know. 

BTW I think I figured out why you [test](https://github.com/xuzhg/WebApiSample/blob/master/v6.x/WebApi6xFeaturesTest/Complex/ComplexTypeTest.cs) worked, it's because the objects don't have an `Id`, so I suppose OData is handling them as Complex Objects.

Thanks.

**Comment by xuzhg** [comment]
@alexandrevribeiro Cool. Please let me know if you need more help.

**Comment by alexandrevribeiro** [comment]
@xuzhg It perfectly worked. Thanks a lot!

**Pull request merged**
